name: Rust CI

on:
  pull_request:
  push:

jobs:
  build-and-test:
    uses: iExecBlockchainComputing/github-actions-workflows/.github/workflows/rust-build.yml@rust-build-v2.0.0
    with:
      rust-version: 'stable'
      working-directory: "."
      enable-cache: true
      publish-crates-io: false
