name: Build and Test Rust Package

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    uses: iExecBlockchainComputing/github-actions-workflows/.github/workflows/rust-build.yml@refactor/rust-build-workflow
    with:
      rust-version: '1.85.0'
      build-profile: 'release'
      run-audit: false
      enable-cache: true
