name: Rust CI

on:
  pull_request:
    types: [opened]
  push:

jobs:
  build-and-test:
    uses: iExecBlockchainComputing/github-actions-workflows/.github/workflows/rust-build.yml@rust-build-v2.0.0
    with:
      rust-version: '1.85.0'
      working-directory: "."
      enable-cache: true
      publish-crates-io: false
  
  prepare:
    name: Determine Image Tag
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref_name == 'main' || startsWith(github.ref_name, 'feature/') || startsWith(github.ref_name, 'bugfix/')
    outputs:
      tag: ${{ steps.determine-tag.outputs.tag }}
    steps:
      - name: Determine Docker tag based on Git ref
        id: determine-tag
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-8)

          if [[ "${{ github.ref_name }}" == "main" ]]; then
            TAG_NAME="dev-${SHORT_SHA}"
            echo "Processing main branch push -> ${TAG_NAME}"
          else
            # This covers feature/ and bugfix/ branches
            TAG_NAME="feature-${SHORT_SHA}"
            echo "Processing feature/bugfix branch: ${{ github.ref_name }} -> ${TAG_NAME}"
          fi
          
          echo "tag=${TAG_NAME}" >> "$GITHUB_OUTPUT"
          echo "Determined image tag: ${TAG_NAME}"
  
  build-and-publish:
    name: Build and Publish to Registry
    needs: prepare
    uses: iExecBlockchainComputing/github-actions-workflows/.github/workflows/docker-build.yml@main
    with:
      image-name: docker-regis.iex.ec/tee-worker-pre-compute-rust
      image-tag: ${{ needs.prepare.outputs.tag }}
      dockerfile: Dockerfile
      context: .
      platforms: linux/amd64
      registry: docker-regis.iex.ec
      push: true
      security-scan: true
      security-report: "sarif"
      hadolint: true
    secrets:
      username: ${{ secrets.NEXUS_USERNAME }}
      password: ${{ secrets.NEXUS_PASSWORD }}
