name: Build and Push Release Image

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  prepare:
    name: Determine Image Tag
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.determine-tag.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine Docker tag based on Git ref
        id: determine-tag
        run: |
          # Since this workflow only triggers on tags matching 'v*.*.*' we know we're always dealing with a version tag
          TAG_ON_MAIN=$(git branch -r --contains ${{ github.sha }} 'origin/main')

          if [[ -n "$TAG_ON_MAIN" ]]; then
            TAG_NAME="${{ github.ref_name }}"
            TAG_NAME="${TAG_NAME#v}"  # Remove 'v' prefix
            echo "Processing tag on main branch: ${{ github.ref_name }} -> ${TAG_NAME}"
          else
            echo "Error: Tag ${{ github.ref_name }} is not on main branch"
            echo "Tags must be created on main branch to generate X.Y.Z image tags"
            exit 1
          fi
          
          echo "tag=${TAG_NAME}" >> "$GITHUB_OUTPUT"
          echo "Determined image tag: ${TAG_NAME}"

  build-and-publish:
    name: Build and Publish to Registry On Tag
    needs: prepare
    uses: iExecBlockchainComputing/github-actions-workflows/.github/workflows/docker-build.yml@docker-build-v2.4.0
    with:
      image-name: docker-regis.iex.ec/tee-worker-pre-compute-rust
      image-tag: ${{ needs.prepare.outputs.tag }}
      dockerfile: Dockerfile
      context: .
      registry: docker-regis.iex.ec
      push: true
      security-scan: true
      security-report: "sarif"
      hadolint: true
      platforms: linux/amd64
    secrets:
      username: ${{ secrets.NEXUS_USERNAME }}
      password: ${{ secrets.NEXUS_PASSWORD }}
